### ISSUE TITLE
App size missing in response

### ISSUE THREAD

**Issue by andrekos2** [facundoolano/google-play-api#10]
I tried to replicate the result example from https://github.com/facundoolano/google-play-scraper but i only get the following fields:

![image](https://user-images.githubusercontent.com/26861595/29864436-4d8e13a4-8da5-11e7-8391-4e3178e93890.png)

In particular, I do not have app_size results as part of the output e.g. 

![image](https://user-images.githubusercontent.com/26861595/29864542-a81058be-8da5-11e7-8a1e-c22808268e33.png)

I'd like to learn more about the reasons for the discrepancy for the output on this page https://github.com/facundoolano/google-play-scraper and what I currently get.

**Comment by facundoolano** [comment]
The App size was removed from the Google Play website, and this it stopped appearing in the scraper responses, see https://github.com/facundoolano/google-play-scraper/issues/139

**Comment by andrekos2** [comment]
Yep, I had seen that but decided to ask for more detail. How about other discrepancies? As to the app_size, I had someone commented locally that  Google is filtering traffic per client and provides adequate response. 

![image](https://user-images.githubusercontent.com/26861595/29908898-0b340412-8e56-11e7-8ef4-900845ce48a6.png)

**Comment by facundoolano** [comment]
I'm not sure what those other discrepancies are. I'm closing this since it's not related to this API, you can create an issue in the scraper repo if you want to follow up.
