### ISSUE TITLE
Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by abhijeet0007** [facundoolano/google-play-api#14]
from previous day I just found the error in localhost:3000/api/apps/com.facebook.orca in
{
message: "Cannot read property 'split' of undefined"
}
please help me out to get over with this error

**Comment by sunnyrty** [comment]
me 2 same problem

Cannot read property 'split' of undefined

**Comment by facundoolano** [comment]
https://github.com/facundoolano/google-play-scraper/issues/192

**Comment by sunnyrty** [comment]
@facundoolano thanks for reply... waiting for fix

**Comment by facundoolano** [comment]
This has been fixed in google play scraper, the version should be updated in this project's package.json and check that everything is working.

PRs welcome :)

**Comment by srikanthlogic** [comment]
Bumped package.json version in #18

**Comment by facundoolano** [comment]
THis should be fixed now.
