### ISSUE TITLE
integration in PHP project

### ISSUE THREAD

**Issue by doganoo** [facundoolano/google-play-api#15]
Hey @facundoolano,

I have a PHP project where I need Google Play App data and want to use this library. My first idea was the integration of this project within the PHP project using npm in a folder named "3rdparty" or something similar.

What do you think about this approach? Or is it better to handle the library as a separate project and request the data via REST api?

regards

Dogan

**Comment by facundoolano** [comment]
I don't know enough about PHP nor your specific use case to make a suggestion. Just keep in mind that the scraper is brittle, it can fail when google changes its layout (something it's been happening the last week), or if you make too many requests. 

I think the best approach for a serious project is to have a batch project that periodically runs the scraper and saves the results to a DB. Then your app can take the data from the DB directly.
