### ISSUE TITLE
{"message":"Error requesting Google Play:undefined"}

### ISSUE THREAD

**Issue by NT-ZG** [facundoolano/google-play-api#20]
Hi, did a clean install today and am getting {"message":"Error requesting Google Play:undefined"} when I request: api/apps/com.dxco.pandavszombies/reviews

api/apps/com.dxco.pandavszombies works fine, as do most of the app list requests. "/permissions", and "/similar" also result in the the same error.

Was running scraper 6.04, then upgraded it to 6.1.0 but same error.

**Comment by srikanthlogic** [comment]
Unable to verify. All the mentioned endpoints work fine for me. Maybe it was an intermittent issue?
