### ISSUE TITLE
TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by khoazero123** [facundoolano/google-play-api#27]
Got this error when get info of app: http://localhost:3000/api/apps/com.glu.zbs

![image](https://user-images.githubusercontent.com/2802354/51889429-2c987400-23cc-11e9-884a-f1d4d0735a43.png)

**Comment by facundoolano** [comment]
It's an issue with the scraper https://github.com/facundoolano/google-play-scraper/issues/289

**Comment by facundoolano** [comment]
should be fixed with a npm install
