### ISSUE TITLE
{"message":"Cannot read property 'replace' of undefined"}

### ISSUE THREAD

**Issue by nowkin** [facundoolano/google-play-api#28]
hello,

only getting {"message":"Cannot read property 'replace' of undefined"} since a few days when trying to parse app infos with apps/appid

any ideas?

**Comment by nowkin** [comment]
normal play parser is working fine. i get the problem only in the rest api

**Comment by facundoolano** [comment]
try with `npm install` to update the dependencies

**Comment by ZeeshanSultan** [comment]
Up to date. Still getting the same error 
/api/apps works 
/api/apps/appid fails with the above mentioned error

**Comment by ZeeshanSultan** [comment]
#30 
Fixed

**Comment by srikanthlogic** [comment]
Fixed in #35 Please update

**Comment by billsix123** [comment]
I had the same problem today, but I didn't change anything. It was normal yesterday

**Comment by hmzisb** [comment]
Same problem. Was working fine in the morning. Updated everything, still issue is there.

**Comment by billsix123** [comment]
> 同样的问题。早上工作正常。更新了所有内容，问题仍然存在。

Have you solved this problem now?

**Comment by farzan3** [comment]
i am getting same issue now any one know work around , thanks in advance

**Comment by srikanthlogic** [comment]
Will be fixed with #61

**Comment by Frohlix** [comment]
I'm also getting this with the current version

**Comment by jaredsburrows** [comment]
Try updating the dependencies and install:
```
rm -f package-lock.json && \
npm update && \
npm outdated && \
npm audit fix --force && \
npm install
```

Start the server:
```
npm start
```

Test it out:
```
curl "localhost:3000/api/apps/burrows.apps.crypto"
```
