### ISSUE TITLE
Deployment to now

### ISSUE THREAD

**Issue by ZeeshanSultan** [facundoolano/google-play-api#29]
I tried to deploy it via now. It just uploaded files. Didn't work

https://google-play-api-master-3de2vvg1p.now.sh/

**Comment by facundoolano** [comment]
I haven't try the now deploy in a while, the instructions in the README are probably updated by now. If you figure it out, please send a PR to fix it.

**Comment by ZeeshanSultan** [comment]
Fixed #30
