### ISSUE TITLE
Error displayed when trying to run server.js

### ISSUE THREAD

**Issue by kani04** [facundoolano/google-play-api#31]
The server starts in localhost:3000 when executing "node server.js" command

The Webpage displays the following error:

Cannot GET /

If anyone has solution to this, Please guide me...

**Comment by facundoolano** [comment]
How about another url like `/api/apps/`

**Comment by kani04** [comment]
This site can’t be reached error

**Comment by kani04** [comment]
Thanks for your support.
Hi I am able to get nearly 40 reviews by using 
"http://localhost:3000/api/apps/com.king.petrescuesaga/reviews/"

Can you please suggest how I can get more reviews through this api.
I want to continuously crawl data

**Comment by srikanthlogic** [comment]
Use the next key in the result in the response and keep navigating till you find them.

api/apps/com.king.petrescuesaga/reviews/?page=1

**Comment by kani04** [comment]
Thank you :-)
