### ISSUE TITLE
Order of results

### ISSUE THREAD

**Issue by ZeeshanSultan** [facundoolano/google-play-api#33]
I simply searched for facebook and it's not the top 5 results in the API even though it's on number one in the playstore

Example deployment.
https://google-play-api.zeeshi7897.now.sh/api/apps/?apps=facebook

**Comment by facundoolano** [comment]
That's not the way to search. You can see the example in the README `GET /api/apps/?q=facebook`. But [search is currently broken](https://github.com/facundoolano/google-play-api/issues/32) due to a change in the Google Play HTML.
