### ISSUE TITLE
Cannot retrieve attributes and some pages (reviews, similar, etc)

### ISSUE THREAD

**Issue by marceloeler** [facundoolano/google-play-api#39]
Hi. I used your api three months ago and everything went fine.
I tried to used again today and it seems there is something wrong. For instance, I try to access the reviews of an app (e.g. http://localhost:3000/api/apps/com.whatsapp/reviews), I get this result: {"message":"App not found (404)"}.

Do you have any idea of what is going on?

**Comment by marceloeler** [comment]
I solved the issues by updating the scraper version to 7.0.1 on package.json

**Comment by facundoolano** [comment]
Do you mind sending a PR to update the package.json?
