### ISSUE TITLE
Need to gracefully handle apps that are in "pre-register" mode

### ISSUE THREAD

**Issue by sgargbugreporter** [facundoolano/google-play-api#4]
When trying to retrieve information for Google Allo (https://play.google.com/store/apps/details?id=com.google.android.apps.fireball) which is mentioned as being in "Pre-Register", I am getting errors.  It does not have the "max/min download listed".

Because of this the API gives an error (mapping port 33333 to the server's 3000):

`$ curl http://localhost:33333/api/apps/com.google.android.apps.fireball/`

Error message:
`{"message":"Unable to parse min/max downloads: , "}`

Also see [google-play-scraper issue 115](https://github.com/facundoolano/google-play-scraper/issues/115)

**Comment by facundoolano** [comment]
Fixed by updating the google-play-scraper version.
