### ISSUE TITLE
Cannot read property replace of undefined

### ISSUE THREAD

**Issue by hmzisb** [facundoolano/google-play-api#59]
Getting this response for every app:
{"message":"Cannot read property 'replace' of undefined"}

**Comment by facundoolano** [comment]
Duplicated, install the latest version.

**Comment by hmzisb** [comment]
Using the latest version. Was working fine yesterday.

**Comment by hmzisb** [comment]
@facundoolano Thanks for the fast response. I re-installed it but still have the same issue. All pages work except the app info page.

**Comment by facundoolano** [comment]
Sorry, I thought this was the google-play-scraper repo. Try upgrading the google-play-scraper dependency

**Comment by hmzisb** [comment]
Just upgraded the dependency to 8.0.3 but still no luck. Even tried reinstalling. Can you please have a look? Thank you

**Comment by hmzisb** [comment]
@billsix123 also reported this in another thread.

**Comment by hmzisb** [comment]
@facundoolano Sorry to disturb you but have you got time to look at it. I recently built a complete project on it and it just finished a day earlier and now API isn't working. I am a PHP guy so it will take me forever to fix. Thanks for the help.

**Comment by hmzisb** [comment]
Sorry, updating and restarting the process fixed it. Thank you very much.
