### ISSUE TITLE
{"message":"Cannot read property 'replace' of undefined"}

### ISSUE THREAD

**Issue by lau1944** [facundoolano/google-play-api#60]
When i try to fetch app detail, it shows this error 
```
/api/apps/com.zhiliaoapp.musically
```
```
{"message":"Cannot read property 'replace' of undefined"}
```

**Comment by BELAABED-Med** [comment]
> When i try to fetch app detail, it shows this error
> 
> ```
> /api/apps/com.zhiliaoapp.musically
> ```
> 
> ```
> {"message":"Cannot read property 'replace' of undefined"}
> ```

I get the same issue, the solution is to update the version of google-play-scrapper to 8.0.4
