### ISSUE TITLE
App details not getting properly.

### ISSUE THREAD

**Issue by eldhosejoys** [facundoolano/google-play-api#67]
Seeing error while trying to get app detail. I think Google might have changed the structure of the page or something.

{"message":"Cannot read property 'replace' of undefined"}

**Comment by hmzisb** [comment]
Same problem. Have you been able to fix it?

**Comment by facundoolano** [comment]
this was because of an issue with the used google play version. try updating it to the latest one (feel free to send a PR with that change)
