### ISSUE TITLE
Incorrect playstoreUrl

### ISSUE THREAD

**Issue by chinlun** [facundoolano/google-play-api#7]
playstoreUrl attribute in /app/<Id> endpoint doesn't always returns the correct URL. Sometimes it give me an url with my host name instead of Google play store's host name.

**Comment by facundoolano** [comment]
Can you show me a code sample to reproduce the error?

**Comment by chinlun** [comment]
Hi @facundoolano,

I don't have a sample url on public domain as I am only testing it on local. Following is the url on my local machine.

http://local.mediamath.com:3000/api/apps/com.rovio.baba

The playstoreUrl will only show the correct url on the first time. If you refresh it, it will use my own host name instead of Google Play's. I also noticed the developer.devId attribute will keep adding a sub level attribute on every refresh.

**Comment by facundoolano** [comment]
ok, I was able to reproduce. It happens with all apps actually. Let me look into it.

**Comment by facundoolano** [comment]
Pushed a fix, thanks for reporting!
