### ISSUE TITLE
App detail endpoint not working

### ISSUE THREAD

**Issue by kuwapa** [facundoolano/google-play-api#81]
I just cloned this repo and was trying it out. The endpoint `/api/apps/org.wikipedia/` isn't working. It returns this following result. Other endpoints are working though. How can I fix this? Thanks. 

```
{
"message": "Cannot read properties of undefined (reading 'replace')"
}
```

**Comment by nathannli** [comment]
did you try using this fix?
https://github.com/facundoolano/google-play-api/pull/76
