### ISSUE TITLE
Failed with error: {"message":"Cannot read properties of undefined (reading 'replace')"}

### ISSUE THREAD

**Issue by nithi2023** [facundoolano/google-play-api#83]
I have tried an app details endpoint: `http://localhost:443/api/apps/org.wikipedia/?lang=es`

and got this error: `{"message":"Cannot read properties of undefined (reading 'replace')"}`

I could't able to figure out the issue.

**Comment by nathannli** [comment]
did you try using this fix?
https://github.com/facundoolano/google-play-api/pull/76

**Comment by canalamh2** [comment]
mesmo erro

**Comment by ucf0709** [comment]
go to project root : node_modules\google-play-scraper\lib\app.js

replace all ds:4 with  ds:5
then replace ds:8 with ds:9

**Comment by jaredsburrows** [comment]
This is a duplicate of https://github.com/facundoolano/google-play-api/issues/28.

**Comment by facundoolano** [comment]
should be fixed on latest version
