### ISSUE TITLE
Unable to request apps details beyond default numbers 

### ISSUE THREAD

**Issue by lucky-singh** [facundoolano/google-play-api#9]
I am trying following string but it's not giving any result.

string: http://localhost:3000/api/apps?category=MEDICAL&start=240&num=120&fullDetail=true&throttle=10
Output: {"message":"Error requesting Google Play:undefined"}

When I actually browse to the webpage, it doesn't list more apps and requires scrolling. After 300 I need to press See More to get more apps.

Could you please suggest what can be done, I wanted as many as result as possible.

**Comment by facundoolano** [comment]
This is likely due to an outdated version of Google play scraper being used in this project. Can you try updating it and send a PR if it works?

**Comment by lucky-singh** [comment]
I just checked the version, it's 3.2.4. Could you please confirm the latest version.

**Comment by facundoolano** [comment]
3.2.4 is the latest one

**Comment by facundoolano** [comment]
is this still not working on the latest code?

**Comment by lucky-singh** [comment]
Didn't try afterwords. Thank you for asking.

**Comment by srikanthlogic** [comment]
Tried 

http://localhost:3000/api/apps?category=MEDICAL&start=240&num=120&fullDetail=true&throttle=10
http://localhost:3000/api/apps?category=MEDICAL&start=360&num=120&fullDetail=true&throttle=10

with v.6.1.0 scraper and it works fine for me.

**Comment by facundoolano** [comment]
fixed by #21
